name: demo

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  date:
    runs-on: windows-latest

    steps:
      - name: first
        run: date

      
   
   
